### ISSUE TITLE
Set what extension file don't want to copy or be ignore it

### ISSUE THREAD

**Issue by benchohuerta** [hezral/clips#35]
I would like can set a specific extension file type that i don't want to be copied.
* example:
If I copy a ".mp3" to another folder, I am not interested in seeing that data in "Clips" if I do not intend to use its "URL".

**Comment by hezral** [comment]
thanks for the suggestion.

if i understand this

1. User copies files
2. Clips detects the copy event, omits filetypes specified by user in settings
3. Clips records the filtered clip item

Is that correct?

**Comment by hezral** [comment]
this is implemented in dev, you can test it out and let me know if any feedbacks. 
for now will close this issue. 
this new option overrides the excluded apps since it filters by keyword

https://github.com/hezral/clips/actions/runs/1521562912

![image](https://user-images.githubusercontent.com/762735/144349476-fc588768-29dd-49f3-9930-b0c69a04ec83.png)
